### ISSUE TITLE
BLE Client Library / Home Assistant Integration

### ISSUE THREAD

**Issue by chkuendig** [Sensirion/arduino-ble-gadget#13]
I'm looking to read the measurements from a SCD4x CO₂ Gadget to my computer/homeserver (mostly to get them into Home Assistant). 

I noticed that this library implements the whole BT protocol from the "sender/encoder" side - is there also a library to consume this data? (i.e. identify the devices, capture the broadcast data and parse it, and send commands to fetch all data etc.)

**Comment by chkuendig** [comment]
Update: I started this myself custom-components/ble_monitor#686

**Comment by psachs** [comment]
Thanks for sharing. Since you could solve the issue yourself I will close it
