### ISSUE TITLE
Compilation Problem std::round(result[0]))

### ISSUE THREAD

**Issue by Alexej1993** [Sensirion/arduino-ble-gadget#14]
there is a compilation problem
has anyone met that?

C:\Users\alexe\AppData\Local\Temp\arduino_modified_sketch_996125\Example3_SCD30_BLE_TTGO_Gadget.ino: In function 'void loop()':

Example3_SCD30_BLE_TTGO_Gadget:145:29: error: 'round' is not a member of 'std'

       displayCo2((uint16_t) std::round(result[0]));

                             ^

C:\Users\alexe\AppData\Local\Temp\arduino_modified_sketch_996125\Example3_SCD30_BLE_TTGO_Gadget.ino:145:29: note: suggested alternative:

In file included from C:\Users\alexe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/esp32-hal.h:34:0,

                 from C:\Users\alexe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/Arduino.h:35,

                 from sketch\Example3_SCD30_BLE_TTGO_Gadget.ino.cpp:1:

C:\Users\alexe\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6/tools/sdk/include/newlib/math.h:278:15: note:   'round'

 extern double round _PARAMS((double));

               ^

exit status 1

c

**Comment by psachs** [comment]
you might have to get rid of the std::round method and e.g. just cast it to an integer. Since you are displaying CO2 ppm values it doesn't make that much of difference if you round correctly or not. The error is negligible.
