### ISSUE TITLE
Access to internal storage-data via matlab 

### ISSUE THREAD

**Issue by PascalSwissoptic** [Sensirion/arduino-ble-gadget#21]
Dear,
i'm from a big company in switzerland and we really love your SHT4x Smart-Gadget sensors (and we own more than 200 pieces of it). For our internal workflow we would like to write an programm to get the data directly out of the sensors via our own customized gui... hopefully you can help us for a very specific question.

i called to your colleague today and he pleased me to post my question here:

We established a BLE connection (works very stable) and we were able to read and write specific values via our program. We have not found a way for accessing the internal storage and fetch all the data. we found out that the service-UUID "00008000-B38D-4985-720E-0F993A68EE41" are for internal storage actions. Further we found out, that we can easily get the loggerInterval by acessing the UUID "00008001-B38D-4985-720E-0F993A68EE41" and the stored sample count 
 by acessing "00008002-B38D-4985-720E-0F993A68EE41".

So far so good: But we are not sure about  UUID "00008003-B38D-4985-720E-0F993A68EE41" - what does this do? If we read the notify-only UUID "00008004-B38D-4985-720E-0F993A68EE41", we get a batch of 20 uint8-values, (like e.g. 9     0    55   104    93   112   236   105    72   106    16   105   189   109   218   104    48   111     0     0) wich is probably a value convolut (Timestamps, humidity, tempertaure,...)? - how is this encoded?
How can we acitvate the download of the values - are they submitted over the notify readout and does we have to do. 

We would like to buy a lot of new sensors - if we found a solution for downloading the internal storage data.
Hope we find a solution ;)

Best,
Pascal

**Comment by PascalSwissoptic** [comment]
![Unbenannt](https://user-images.githubusercontent.com/111435905/185142097-a8af63e7-20d0-4b02-a0f9-a4b21db63fdd.PNG)

**Comment by qfisch** [comment]
The mentioned piece of documentation is now available.
You will find it [there](../blob/master/documents/Sensirion_BLE_communication_protocol.pdf)
We hope it will be answer your questions
