### ISSUE TITLE
Sensirion SCD4x CO₂ Gadget  only displays co2 values, no temp or humidity.

### ISSUE THREAD

**Issue by jackloomen** [Sensirion/arduino-ble-gadget#27]
Don't know if that's the right place for it but no other repo seems more relevant.

Would it be possible to update the firmware of the SCD4x CO₂ Gadget [1] to provide the MyAmbiance app with temperature and humidity values? Currently it only displays co2.

[1] https://sensirion.com/products/catalog/SCD4x-CO2-Gadget/

**Comment by LeonieFierz** [comment]
Thank you for contacting us.

The CO2 Gadget does not provide temperature and humidity values and we do not plan a firmware update to do so.

**Comment by jackloomen** [comment]
What about adding functionality to turn off auto-calibration and trigger manual calibration?
