### ISSUE TITLE
Data Points Question

### ISSUE THREAD

**Issue by KASSIMSAMJI** [Sensirion/arduino-ble-gadget#32]
Hi There

I am using this example here, unmodified

https://github.com/Sensirion/arduino-ble-gadget/blob/master/examples/Example1_MockedReadings/Example1_MockedReadings.ino

but, taking a look at the manage gadget section on the app, the data points keep increasing so fast

the figure gets to thousands in couple of few seconds, is this why the app ( only when in "plot tab", "dashboard tab" works fine all the time ) sometimes locks up ?

<img width="240" alt="app" src="https://github.com/Sensirion/arduino-ble-gadget/assets/89432773/3ef35d30-325c-44c1-9fc7-1efbf4cb3147">

**Comment by qfisch** [comment]
Hej @KASSIMSAMJI ,

It is an issue we encountered as well with DIY sensors.
We believe it is an issue on MyAmbience, it is planned to have a look into it but it is not on top priority (to be honest).
Your report should push us to investigate faster.
I will definitely keep you up to date.

Cheers
Q
