### ISSUE TITLE
SCD30 forced calibration within MyAmbiance? 

### ISSUE THREAD

**Issue by hallinen** [Sensirion/arduino-ble-gadget#39]
I really like the ability to do calibration of the SCD40/41 within the MyAmbiance app.  Of course I want to be able to do it with the SCD30 too!  Is that possible?  If not, do you know of an Arduino sketch that does forced calibration?  I've been having trouble using what limited stuff is out there. I'm not clever enough to do it from the data sheet. Thank you.

**Comment by psachs** [comment]
Hi,

our Arduino driver implements the force calibration for SCD30 (see: https://github.com/Sensirion/arduino-i2c-scd30/blob/master/src/SensirionI2cScd30.h#L217)

However we don't have a ready to use example for it yet. To do a force re-calibration you have to run the SCD30 for at lease 2 minutes in a stable environment, before setting the reference value of this environment. 
In MyAmbience we currently have no plan to  to support force re-calibration of SCD30 sensors.

Let me know if you need further support.
