### ISSUE TITLE
[Feature request] Support for ESP32-C6

### ISSUE THREAD

**Issue by troglodisme** [Sensirion/arduino-ble-gadget#43]
I can't compile any of the examples on a ESP32-C6 board (specifically Sparkfun ESP32-C6 Thing Plus). I believe this is due to an issue with NimBLE library you are using. Can you please suggest a solution?

`In file included from /Users/giulio/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-b6b4727c58/esp32c6/include/bt/include/esp32c6/include/esp_bt.h:17,
                 from /Users/giulio/GitHub/resources/Arduino/libraries/NimBLE-Arduino/src/NimBLEDevice.h:46,
                 from /Users/giulio/GitHub/resources/Arduino/libraries/Sensirion_Gadget_BLE_Arduino_Lib/src/NimBLELibraryWrapper.cpp:2:
/Users/giulio/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-b6b4727c58/esp32c6/include/bt/common/api/include/api/../../../../controller/esp32c6/esp_bt_cfg.h:19:10: fatal error: syscfg/syscfg.h: No such file or directory
   19 | #include "syscfg/syscfg.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.`

**Comment by LeonieFierz** [comment]
Hi @troglodisme 

Your assumption is right, the NimBLE lib unfortunately does not support the ESP32-C6 yet. However, there is a feature request for it and there is already a branch with a test implementation which seems to work. See https://github.com/h2zero/NimBLE-Arduino/issues/642

If this does not work out, you could plug in another BLE lib by implementing the src/IBLELibraryWrapper.h.

Best, Léonie

**Comment by davidkreidler** [comment]
I've tried my luck **without success** on two different esp32-c6 boards using the "esp32-c6-test" branch.
https://github.com/h2zero/NimBLE-Arduino/tree/esp32-c6-test
The gadget simply did not show up in the Sensirion MyAmbience app.

The NimBLE-Arduino example code here worked https://github.com/h2zero/NimBLE-Arduino/tree/esp32-c6-test/examples/NimBLE_Client . I was able to see Bluetooth devices around reported by the esp32-c6 itself via serial.

The same branch but on an esp32-S3 was successful. I will look next into the messages further down in the issue https://github.com/h2zero/NimBLE-Arduino/issues/642.

**Comment by troglodisme** [comment]
Thanks @davidkreidler and @LeonieFierz 

Interesting that you could get the esp32-c6-test branch to work for the NimBLE_Client example. If my case it doesn't successfully finish compilation process. Could you please share your setup?

**Comment by davidkreidler** [comment]
Arduino IDE 2.3.2
esp32 by Espressif Systems 3.0.3
NimBLE-Arduino branch esp32-c6-test
Sensirion core 0.7.1
Sensirion Gadget BLE Arduino Lib 1.3.2
Sensirion  I2C SCD4X 0.4.0
Sensirion  UTP CORE 0.4.0

**Comment by LeonieFierz** [comment]
Hi @troglodisme
As we do not have a esp32-c6 available for testing I cannot test it myself. Did you try running the NimBLE_Server example?

**Comment by troglodisme** [comment]
> Hi @troglodisme As we do not have a esp32-c6 available for testing I cannot test it myself. Did you try running the NimBLE_Server example?

Thanks @LeonieFierz . We are happy to provide you with an esp32-c6 to test with? let me know how. Alternatively, you could just try and build the code for that board - I think you'll experience the same as me and the code will not compile unfortunately.

**Comment by LeonieFierz** [comment]
@troglodisme 
We will have a look into compiling and running the Arduino BLE Gadget on a ESP32-C6 Board within the next weeks and get back to you.
