### ISSUE TITLE
Use of SVM30

### ISSUE THREAD

**Issue by Enoch23** [Sensirion/arduino-ble-gadget#6]
First off, thank you again for your support helping me get things working with my SCD30!

I have a SVM30 and was curious if the SVM40 Example (Example 5) could be easily adapted for this older version? Aside from changing the I2C address in the line:
`const int16_t SVM40_ADDRESS = 0x6A;`
are there any other changes I need to be aware of?

**Comment by rnestler** [comment]
SVM30 is quite different from the SVM40. The SVM40 has a separate micro controller which reads the sensors and applies the VOC Index Algorithm to calculate.

The SVM30 is just a PCB with the two sensors (SGP30 and SHTC1), power supply and level shifters. it is not recommended for new designs.

See https://github.com/Sensirion/embedded-sgp for a driver for the SVM30 module.
